"use client";

import { useEffect, useState } from "react";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
} from "recharts";

type Stats = {
  users: number;
  activeSubscriptions: number;
  revenueCents: number;
};

type RevenueByMonth = { month: string; revenue: number };
type SubscriptionsByPlan = { name: string; count: number };
type UsersByMonth = { month: string; count: number };
type SubscriptionsByStatus = { status: string; count: number };

export default function AdminDashboard() {
  const [stats, setStats] = useState<Stats | null>(null);

  const [revenueByMonth, setRevenueByMonth] = useState<RevenueByMonth[]>([]);
  const [subscriptionsByPlan, setSubscriptionsByPlan] = useState<
    SubscriptionsByPlan[]
  >([]);
  const [usersByMonth, setUsersByMonth] = useState<UsersByMonth[]>([]);
  const [subscriptionsByStatus, setSubscriptionsByStatus] = useState<
    SubscriptionsByStatus[]
  >([]);

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadData() {
      try {
        const [statsRes, chartsRes] = await Promise.all([
          fetch("/api/admin/stats"),
          fetch("/api/admin/charts"),
        ]);

        const statsData = await statsRes.json();
        const chartsData = await chartsRes.json();

        if (statsData.success) {
          setStats(statsData.stats);
        }

        if (chartsData.success) {
          setRevenueByMonth(chartsData.revenueByMonth ?? []);
          setSubscriptionsByPlan(chartsData.subscriptionsByPlan ?? []);
          setUsersByMonth(chartsData.usersByMonth ?? []);
          setSubscriptionsByStatus(chartsData.subscriptionsByStatus ?? []);
        }
      } finally {
        setLoading(false);
      }
    }

    loadData();
  }, []);

  return (
    <div className="space-y-14">
      <h1 className="text-3xl font-bold">Admin Dashboard</h1>

      {/*KPIs*/}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <KpiCard title="Users" value={stats?.users} loading={loading} />
        <KpiCard
          title="Active Subscriptions"
          value={stats?.activeSubscriptions}
          loading={loading}
        />
        <KpiCard
          title="Monthly Revenue"
          value={stats ? `$${(stats.revenueCents / 100).toFixed(2)}` : null}
          loading={loading}
        />
      </div>

      {/*Charts*/}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <ChartCard title="Revenue Over Time" loading={loading}>
          {!loading && (
            <>
              <ResponsiveContainer width="100%" height={300}>
                <LineChart data={revenueByMonth}>
                  <XAxis dataKey="month" />
                  <YAxis />
                  <Tooltip />
                  <Line type="monotone" dataKey="revenue" strokeWidth={2} />
                </LineChart>
              </ResponsiveContainer>

              <ChartDescription>
                Monthly recurring revenue generated by active subscriptions.
              </ChartDescription>

              {revenueByMonth.length === 0 && (
                <Insight type="warning">No revenue recorded yet.</Insight>
              )}
            </>
          )}
        </ChartCard>

        <ChartCard title="Subscriptions by Plan" loading={loading}>
          {!loading && (
            <>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={subscriptionsByPlan}>
                  <XAxis dataKey="name" />
                  <YAxis />
                  <Tooltip />
                  <Bar dataKey="count" />
                </BarChart>
              </ResponsiveContainer>

              <ChartDescription>
                Distribution of active subscriptions across plans.
              </ChartDescription>

              {subscriptionsByPlan.length === 0 && (
                <Insight type="info">
                  No active subscriptions found yet.
                </Insight>
              )}
            </>
          )}
        </ChartCard>

        <ChartCard title="New Users Over Time" loading={loading}>
          {!loading && (
            <>
              <ResponsiveContainer width="100%" height={300}>
                <LineChart data={usersByMonth}>
                  <XAxis dataKey="month" />
                  <YAxis />
                  <Tooltip />
                  <Line type="monotone" dataKey="count" strokeWidth={2} />
                </LineChart>
              </ResponsiveContainer>

              <ChartDescription>
                Number of new users registered each month.
              </ChartDescription>
            </>
          )}
        </ChartCard>

        <ChartCard title="Subscription Status Breakdown" loading={loading}>
          {!loading && (
            <>
              <ResponsiveContainer width="100%" height={300}>
                <PieChart>
                  <Pie
                    data={subscriptionsByStatus}
                    dataKey="count"
                    nameKey="status"
                    outerRadius={100}
                    label
                  >
                    {subscriptionsByStatus.map((_, i) => (
                      <Cell key={i} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>

              <ChartDescription>
                Breakdown of subscriptions by current status.
              </ChartDescription>
            </>
          )}
        </ChartCard>
      </div>
    </div>
  );
}

/*UI Components*/

function KpiCard({
  title,
  value,
  loading,
}: {
  title: string;
  value?: string | number | null;
  loading: boolean;
}) {
  return (
    <div className="rounded bg-white p-6 shadow">
      <p className="text-sm text-gray-500">{title}</p>

      {loading ? (
        <div className="mt-3 h-8 w-24 animate-pulse rounded bg-gray-200" />
      ) : (
        <p className="mt-2 text-3xl font-bold">{value}</p>
      )}
    </div>
  );
}

function ChartCard({
  title,
  loading,
  children,
}: {
  title: string;
  loading: boolean;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded bg-white p-6 shadow">
      <h2 className="text-xl font-semibold mb-4">{title}</h2>

      {loading ? (
        <div className="h-75 animate-pulse rounded bg-gray-200" />
      ) : (
        children
      )}
    </div>
  );
}

function ChartDescription({ children }: { children: React.ReactNode }) {
  return <p className="mt-4 text-sm text-gray-600">{children}</p>;
}

function Insight({
  children,
  type,
}: {
  children: React.ReactNode;
  type: "info" | "warning";
}) {
  const styles =
    type === "warning"
      ? "border-yellow-200 bg-yellow-50 text-yellow-700"
      : "border-blue-200 bg-blue-50 text-blue-700";

  return (
    <p className={`mt-3 rounded border p-3 text-sm ${styles}`}>{children}</p>
  );
}
