"use client";

import { useEffect, useState } from "react";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
} from "recharts";

type RevenueByMonth = {
  month: string;
  revenue: number;
};

type RevenueByPlan = {
  name: string;
  revenue: number;
};

export default function AdminRevenuePage() {
  const [mrrCents, setMrrCents] = useState(0);
  const [revenueByMonth, setRevenueByMonth] = useState<RevenueByMonth[]>([]);
  const [revenueByPlan, setRevenueByPlan] = useState<RevenueByPlan[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadRevenue() {
      const res = await fetch("/api/admin/revenue");
      const data = await res.json();

      if (data.success) {
        setMrrCents(data.mrrCents ?? 0);
        setRevenueByMonth(data.revenueByMonth ?? []);
        setRevenueByPlan(data.revenueByPlan ?? []);
      }

      setLoading(false);
    }

    loadRevenue();
  }, []);

  if (loading) {
    return <p className="text-gray-600">Loading revenue…</p>;
  }

  return (
    <div className="space-y-10">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold">Revenue</h1>
        <p className="mt-1 text-sm text-gray-600">
          Monitor your SaaS revenue and growth.
        </p>
      </div>

      {/* 💰 MRR */}
      <div className="rounded bg-white p-6 shadow">
        <p className="text-sm text-gray-500">Monthly Recurring Revenue</p>
        <p className="mt-2 text-3xl font-bold">
          ${(mrrCents / 100).toFixed(2)}
        </p>
      </div>

      {/* Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Revenue over time */}
        <div className="rounded bg-white p-6 shadow">
          <h2 className="text-xl font-semibold mb-4">Revenue Over Time</h2>

          <ResponsiveContainer width="100%" height={300}>
            <LineChart data={revenueByMonth}>
              <XAxis dataKey="month" />
              <YAxis />
              <Tooltip />
              <Line type="monotone" dataKey="revenue" strokeWidth={2} />
            </LineChart>
          </ResponsiveContainer>

          <p className="mt-4 text-sm text-gray-600">
            Monthly revenue generated by active subscriptions.
          </p>

          {revenueByMonth.length === 0 && (
            <p className="mt-3 rounded border border-yellow-200 bg-yellow-50 p-3 text-sm text-yellow-700">
              🔍 No revenue data yet.
            </p>
          )}
        </div>

        {/* Revenue by plan */}
        <div className="rounded bg-white p-6 shadow">
          <h2 className="text-xl font-semibold mb-4">Revenue by Plan</h2>

          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={revenueByPlan}>
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />
              <Bar dataKey="revenue" />
            </BarChart>
          </ResponsiveContainer>

          <p className="mt-4 text-sm text-gray-600">
            Contribution of each plan to total revenue.
          </p>

          {revenueByPlan.length === 0 && (
            <p className="mt-3 rounded border border-blue-200 bg-blue-50 p-3 text-sm text-blue-700">
              ℹ️ No active subscriptions yet.
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
